# ---- API URLs ----
API_HOST_LOCAL = 'localhost:8080'

# ---- API Defaults ----
DEFAULT_API_TIMEOUT = 3000

# ---- Internal checks ---

ORDER_SIDE_BUY = True
ORDER_SIDE_SELL = False
ORDER_TYPE_CALL = True
ORDER_TYPE_PUT = False
UNDERLYING_ETH = 0

VALID_STRIKE = list(range(11))
VALID_ORDER_SIDE = [ORDER_SIDE_BUY, ORDER_SIDE_SELL]
VALID_ORDER_TYPE = [ORDER_TYPE_CALL, ORDER_TYPE_PUT]
VALID_UNDERLYING = [UNDERLYING_ETH]
